MvcSkyAir/Controllers/ManagedController.cs
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;
using MvcSkyAir.Repositories;
using NugetModelSkyAir.Models;

namespace MvcSkyAir.Controllers
{
    public class ManagedController : Controller
    {
        private ISkyAirRepository service;
        public ManagedController(ISkyAirRepository service)
        {
            this.service = service;
        }
        public IActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Login
            (string email, string password)
        {
            Usuario user = await
                this.service.LogInAsync(email, password);
            string token = await this.service
                .GetTokenAsync(email, password);
            if (user != null)
            {
                //SEGURIDAD
                ClaimsIdentity identity =
                    new ClaimsIdentity(
                        CookieAuthenticationDefaults.AuthenticationScheme,
                        ClaimTypes.Name, ClaimTypes.Role);
                Claim claimName =
                    new Claim(ClaimTypes.Name, user.Nombre);
                Claim claimRole = new Claim(ClaimTypes.Role,"ADMIN");
                Claim claimToken = new Claim("TOKEN",token);
                identity.AddClaim(claimRole);
                identity.AddClaim(claimName);
                identity.AddClaim(claimToken);
                ClaimsPrincipal userPrincipal =
                    new ClaimsPrincipal(identity);
                await HttpContext.SignInAsync(
                    CookieAuthenticationDefaults.AuthenticationScheme,
                    userPrincipal);
                TempData["BIENVENIDA"]="Bienvenido " + user.Nombre;
                return RedirectToAction("DataVuelos", "Usuarios");
            }
            else
            {
                ViewData["MENSAJE"] = "Usuario/Password incorrectos";
                return View();
            }
        }

        public async Task<IActionResult> Logout()
        {
            await HttpContext.SignOutAsync
                (CookieAuthenticationDefaults.AuthenticationScheme);
            return RedirectToAction("Index", "Home");
        }

        public async Task<IActionResult> ErrorAcceso()
        {
            return View();
        }
    }
}

MvcSkyAir/Controllers/VuelosController.cs
using Microsoft.AspNetCore.Mvc;
using NugetModelSkyAir.Models;
using MvcSkyAir.Repositories;
using DinkToPdf.Contracts;
using DinkToPdf;
using Microsoft.AspNetCore.Http.Extensions;
using System;
using Rotativa.AspNetCore;
using MvcSkyAir.Services;


namespace MvcSkyAir.Controllers
{
    public class VuelosController : Controller
    {
        private ISkyAirRepository service;
        private LogicAppService logicAppService;
        public VuelosController(ISkyAirRepository service, LogicAppService logicAppService)
        {
            this.logicAppService = logicAppService;
            this.service = service;
        }
        public IActionResult Vuelos()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Vuelos(string origen, string destino,
            DateTime fechaIda, DateTime fechaVuelta, int adultos, int kids)
        {
            List<VueloView> vuelos = await this.service.SearchVueloAsync(origen, destino, fechaIda, kids, adultos);
            ViewData["PASAJEROS"] = kids + adultos;
            return View(vuelos);
        }
        [HttpPost]
        public async Task<IActionResult> Pagar(int idVuelo, int equipajeMano, int equipajeCabina, List<string> asientos,
            decimal precio, List<string> nombre, List<string> documento, List<string> apellido,
            List<string> mail, List<string> telefonoContacto, int idClase)
        {
            List<int> idBilletes = new List<int>();
            for (int i = 0; i < nombre.Count; i++)
            {
                Billete billete = await this.service.CreateBilleteAsync
                    (idVuelo, equipajeMano, equipajeCabina, asientos[i],
                    precio, nombre[i], documento[i], apellido[i], mail[i],
                    telefonoContacto[i], idClase);
                idBilletes.Add(billete.IdBillete);
            }
            TempData["COMPRADO"] = "TU COMPRA SE HA REALIZADO CORRECTAMENTE";
            return RedirectToAction("DetallesViaje", new { idBillete = idBilletes });
        }

        public async Task<IActionResult> Clases(int idVuelo)
        {
            ModelVueloClases model = new ModelVueloClases
            {
                Clases = await this.service.GetClasesAsync(),
                VueloView = await this.service.FindVueloViewByIdAsync(idVuelo)
            };
            return PartialView("_ClasesPartial", model);
        }

        public async Task<IActionResult> AsientosPartial(int idVuelo)
        {
            VueloView vuelo = await this.service.FindVueloViewByIdAsync(idVuelo);
            List<string> asientos = new List<string>();
            ModelVueloAsientos model = new ModelVueloAsientos
            {
                Asientos = asientos,
                Vuelo = vuelo
            };
            return PartialView("_AsientosPartial", model);
        }
        public IActionResult PasajerosPartial(int pasajeros)
        {
            return PartialView("_PasajerosPartial", pasajeros);
        }

        public IActionResult PagoPartial(int pasajeros, List<string> asientos, string clase, int precio)
        {
            ModelResumenPago model = new ModelResumenPago
            {
                Asientos = asientos,
                Clase = clase,
                Pasajeros = pasajeros,
                Precio = precio
            };
            return PartialView("_PagoPartial", model);
        }


        public async Task<IActionResult> BilletesPartial(List<int> idBillete)
        {
            List<BilleteVueloView> billetes = await this.service.GetBilletesViewById(idBillete);
            return PartialView("_BilletePartial", billetes);
        }

        public async Task<ActionResult> ObtenerAsientos(int idVuelo)
        {
            // Tu lógica para obtener la capacidad del vuelo
            List<string> asientos = await this.service.GetAsientosBilletesByVuelo(idVuelo);
            return Json(asientos);
        }

        public IActionResult GestionarReserva()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> GestionarReserva(string apellido, string codvuelo)
        {
            BilleteVueloView billeteView = await this.service.FindBilleteViewByApellidoAndIdVueloAsync(codvuelo, apellido);
            if (billeteView != null)
            {
                return RedirectToAction("DetallesViaje", new { idBillete = billeteView.IdBillete });
            }
            else
            {
                ViewData["MENSAJE"] = "No se encuentra ninguna reserva con el apellido " +
                      apellido + " y código de vuelo " + codvuelo;
                return View();
            }
        }

        //public async Task<IActionResult> DetallesViaje(int idBillete)
        //{
        //    BilleteVueloView billeteView = await this.service.FindBilleteViewByIdAsync(idBillete);
        //    return View(billeteView);
        //}

        public async Task<IActionResult> DetallesViaje(List<int> idBillete)
        {
            List<BilleteVueloView> billetes = await this.service.GetBilletesViewById(idBillete);
            return View(billetes);
        }

        public async Task<IActionResult> BilleteToPdf(List<int> idBillete)
        {
            List<BilleteVueloView> billetes = await this.service.GetBilletesViewById(idBillete);
            string nombrePDF = "Billete_" + DateTime.Now.ToString("ddMMyyyyHHmmss") + ".pdf";
            this.logicAppService.CreatePdf("hacer la url https://api.com?idBillete=2&idBillete=3");
            return new ViewAsPdf("BilleteToPdf", billetes)
            {
                FileName = nombrePDF,
                PageOrientation = Rotativa.AspNetCore.Options.Orientation.Portrait,
                PageSize = Rotativa.AspNetCore.Options.Size.A4
            };
        }

        public IActionResult DescargarPDF(string url)
        {
            List<int> ids = new List<int>();
            string[] parameters = url.Split("&");
            foreach (string text in parameters)
            {
                int num = int.Parse(text.Split("=")[1]);
                ids.Add(num);
            }
            return RedirectToAction("BilleteToPdf", new { idBillete = ids });
        }
    }
}

MvcSkyAir/Views/Shared/_AsientosPartial.cshtml
@model ModelVueloAsientos

<div class="container">
    <div class="plane">
        <div class="cockpit">
        </div>
        <div class="exit exit--front fuselage"></div>
        <ol class="cabin fuselage" id="cabin"></ol>
    </div>
</div>

MvcSkyAir/Views/Shared/_BilletePartial.cshtml
@model List<BilleteVueloView>

@{
    Layout = "";
}
<style>
    body {
        font-family: Arial, sans-serif;
        margin: 0;
        padding: 0;
        background-color: #f2f2f2;
    }

    .ticket {
        width: 80%;
        max-width: 500px;
        margin: 50px auto;
        padding: 20px;
        border-radius: 10px;
        background-color: #fff;
        box-shadow: 0 2px 5px rgba(0, 0, 0, 0.1);
    }

    .header {
        display: flex;
        align-items: center;
        margin-bottom: 20px;
    }

    .logo {
        width: 80px;
        margin-right: 20px;
    }

    .title {
        font-size: 24px;
        margin: 0;
        color: #333;
    }

    .flight-info {
        padding: 20px 0;
        border-top: 1px solid #ccc;
        border-bottom: 1px solid #ccc;
    }

    .flight-row {
        display: flex;
        justify-content: space-between;
        margin-bottom: 10px;
    }

    .label {
        font-weight: bold;
    }

    .barcode {
        padding-top: 20px;
        text-align: center;
    }

        /* Simular código de barras */
        .barcode::before {
            content: "||||||||||||||||||||||||||||||||||||";
            font-size: 20px;
            color: #333;
        }

</style>

@foreach(BilleteVueloView billete in Model){
    string minutosSalida = billete.FechaSalida.TimeOfDay.Minutes.ToString();
    string minutosLlegada = billete.FechaLlegada.TimeOfDay.Minutes.ToString();
    if (minutosLlegada == "0")
    {
        minutosLlegada = "00";
    }
    if (minutosSalida == "0")
    {
        minutosSalida = "00";
    }
<div class="ticket">
    <div class="header">
        <img src="~/img/SkyAir-logo-black.png" alt="SkyAir" class="logo">
    </div>
    <div class="flight-info">
        <div class="flight-row">
            <div class="label">Número de Vuelo:</div>
            <div class="value">@billete.CodVuelo</div>
        </div>
        <div class="flight-row">
            <div class="label">Origen:</div>
            <div class="value">@billete.CiudadOrigen</div>
        </div>
        <div class="flight-row">
            <div class="label">Destino:</div>
            <div class="value">@billete.CiudadDestino</div>
        </div>
        <div class="flight-row">
            <div class="label">Salida:</div>
            <div class="value">
                @billete.FechaSalida.ToLongDateString() @billete.FechaSalida.TimeOfDay.Hours:@minutosSalida
            </div>
        </div>
        <div class="flight-row">
            <div class="label">Llegada:</div>
            <div class="value">
                @billete.FechaLlegada.ToLongDateString()  @billete.FechaLlegada.TimeOfDay.Hours:@minutosLlegada
            </div>
        </div>
        <div class="flight-row">
            <div class="label">Clase:</div>
            <div class="value">
                    @billete.Clase
            </div>
        </div>
        <div class="flight-row">
            <div class="label">Asiento</div>
            <div class="value">
                    @billete.Asiento
            </div>
        </div>
        <div class="flight-row">
            <div class="label">Equipaje Cabina</div>
            <div class="value">
                    @billete.EquipajeCabina
            </div>
        </div>
        <div class="flight-row">
            <div class="label">Equipaje Mano</div>
            <div class="value">
                    @billete.EquipajeMano
            </div>
        </div>
        <div class="flight-row">
            <div class="label">Avion</div>
            <div class="value">
                @billete.Avion
            </div>
        </div>
        <div class="flight-row">
            <div class="label">Compra realizada</div>
            <div class="value">
                    @billete.FechaCompra
            </div>
        </div>
    </div>
    
    <div class="barcode">
        <!-- Código de barras aquí -->
    </div>
</div>
}

MvcSkyAir/Views/Shared/_ClasesPartial.cshtml
@model ModelVueloClases


@foreach (TipoClase clase in Model.Clases)
{
    decimal precio = Model.VueloView.PrecioEstandar;
    @if (clase.IdTipoClase == 2)
    {
        decimal percentage = (decimal) 1.10;
        precio= decimal.Multiply(precio,percentage);
    }
        precio = Math.Round(precio,2);
    <div class="col-md-6">
        <div class="card mb-4 rounded-3 shadow-sm">
            <div class="card-header py-3 bg-primary text-white">
                <h4 class="my-0 fw-normal">@clase.Nombre</h4>
            </div>
            <div class="card-body">
                <h1 class="card-title pricing-card-title">@precio €</h1>
                <ul class="list-unstyled mt-3 mb-4">
                    <p>Incluye:</p>
                    <li>Equipaje de mano: @clase.EquipajeMano maleta</li>
                    <li>Equipaje en cabina: @clase.EquipajeCabina</li>
                </ul>
                <button type="button"
                        class="btn btn-primary next-step btn-clase"
                    onclick="seleccionarClase(@clase.IdTipoClase,@precio)">
                    Seleccionar
                </button>
            </div>
        </div>
    </div>
}

MvcSkyAir/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="utf-8">
    <title>@ViewData["Title"] - SkyAir</title>
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta content="" name="keywords">
    <meta content="" name="description">
    <!-- Icon Font Stylesheet -->
    <script src="https://kit.fontawesome.com/87ad13e327.js" crossorigin="anonymous"></script>
    <!-- Libraries Stylesheet -->
    <link href="~/lib/owlcarousel/assets/owl.carousel.min.css" rel="stylesheet">
    <link href="~/lib/lightbox/css/lightbox.min.css" rel="stylesheet">

    <link rel="icon" type="image/x-icon" href="~/favicon.ico">
    <!-- Customized Bootstrap Stylesheet -->
    <link href="~/lib/bootstrap/dist/css/bootstrap.css" rel="stylesheet">

    <!-- Template Stylesheet -->
    <link href="~/css/style.css" rel="stylesheet">
    @RenderSection("Styles", required: false)

</head>

<body class="position-relative">

    <!-- Spinner Start -->
    <div id="spinner" class="show bg-white position-fixed translate-middle w-100 vh-100 top-50 start-50 d-flex align-items-center justify-content-center">
        <div class="spinner-border text-primary" style="width: 3rem; height: 3rem;" role="status">
            <span class="sr-only">Loading...</span>
        </div>
    </div>
    <!-- Spinner End -->
    <!-- Topbar Start -->
    <div class="container-fluid bg-primary px-5 d-none d-lg-block">
        <div class="row gx-0">
            <div class="col-lg-8 text-center text-lg-start mb-2 mb-lg-0">
                <div class="d-inline-flex align-items-center" style="height: 45px;">
                    <a class="btn btn-sm btn-outline-light btn-sm-square rounded-circle me-2" href=""><i class="fab fa-twitter fw-normal"></i></a>
                    <a class="btn btn-sm btn-outline-light btn-sm-square rounded-circle me-2" href=""><i class="fab fa-facebook-f fw-normal"></i></a>
                    <a class="btn btn-sm btn-outline-light btn-sm-square rounded-circle me-2" href=""><i class="fab fa-linkedin-in fw-normal"></i></a>
                    <a class="btn btn-sm btn-outline-light btn-sm-square rounded-circle me-2" href=""><i class="fab fa-instagram fw-normal"></i></a>
                    <a class="btn btn-sm btn-outline-light btn-sm-square rounded-circle" href=""><i class="fab fa-youtube fw-normal"></i></a>
                </div>
            </div>
            <div class="col-lg-4 text-center text-lg-end">
                <div class="d-inline-flex align-items-center" style="height: 45px;">
                    <a asp-controller="Usuarios" asp-action="DataVuelos"><small class="me-3 text-light"><i class="fa fa-sign-in-alt me-2"></i>Login</small></a>

                </div>
            </div>
        </div>
    </div>
    <!-- Topbar End -->
    <!-- Navbar & Hero Start -->
    <div class="container-fluid position-relative p-0">
        <nav class="navbar navbar-expand-lg navbar-light px-4 px-lg-5 py-3 py-lg-0">
            <a class="navbar-brand p-0"
               asp-controller="Home"
               asp-action="Index">
                <img src="~/img/SkyAir-logo-black.png" alt="Logo">
            </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse">
                <span class="fa fa-bars"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarCollapse">
                <div class="navbar-nav ms-auto py-0">
                    <a asp-controller="Home" asp-action="Index" class="nav-item nav-link">Home</a>
                    <a href="about.html" class="nav-item nav-link">About</a>
                    <div class="nav-item dropdown">
                        <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown">
                            Tus vuelos
                        </a>
                        <div class="dropdown-menu m-0">
                            <a asp-controller="Vuelos" asp-action="GestionarReserva" class="dropdown-item">Estado de tu vuelo</a>
                            <a href="#" class="dropdown-item">Gestiona tu reserva</a>
                        </div>
                    </div>
                    <a href="contact.html" class="nav-item nav-link">Contact</a>
                </div>
            </div>
        </nav>
    </div>
    <!-- Navbar & Hero End -->

    <main role="main">
        @RenderBody()
    </main>

    <!-- Footer Start -->
    <div class="container-fluid footer py-5">
        <div class="container py-5">
            <div class="row g-5">
                <div class="col-md-6 col-lg-6 col-xl-3">
                    <div class="footer-item d-flex flex-column">
                        <h4 class="mb-4 text-white">Información</h4>
                        <a href="" class="mb-3"><i class="fas fa-envelope me-2"></i> crisjimenez19@gmail.com</a>
                        <div class="d-flex align-items-center">
                            <i class="fas fa-share fa-2x text-white me-2"></i>
                            <a class="btn-square btn btn-primary rounded-circle mx-1" href="#"><i class="fab fa-facebook-f"></i></a>
                            <a class="btn-square btn btn-primary rounded-circle mx-1" href="#"><i class="fab fa-twitter"></i></a>
                            <a class="btn-square btn btn-primary rounded-circle mx-1" href="#"><i class="fab fa-instagram"></i></a>
                            <a class="btn-square btn btn-primary rounded-circle mx-1" href="https://www.linkedin.com/in/cristopher-jimenez-jimenez/"><i class="fab fa-linkedin-in"></i></a>
                        </div>
                    </div>
                </div>
                <div class="col-md-6 col-lg-6 col-xl-3">
                    <div class="footer-item d-flex flex-column">
                        <h4 class="mb-4 text-white">Company</h4>
                        <a href=""><i class="fas fa-angle-right me-2"></i> About</a>
                        <a href=""><i class="fas fa-angle-right me-2"></i> Careers</a>
                        <a href=""><i class="fas fa-angle-right me-2"></i> Blog</a>
                        <a href=""><i class="fas fa-angle-right me-2"></i> Press</a>
                        <a href=""><i class="fas fa-angle-right me-2"></i> Gift Cards</a>
                        <a href=""><i class="fas fa-angle-right me-2"></i> Magazine</a>
                    </div>
                </div>
                <div class="col-md-6 col-lg-6 col-xl-3">
                    <div class="footer-item d-flex flex-column">
                        <h4 class="mb-4 text-white">Support</h4>
                        <a href=""><i class="fas fa-angle-right me-2"></i> Contact</a>
                        <a href=""><i class="fas fa-angle-right me-2"></i> Legal Notice</a>
                        <a href=""><i class="fas fa-angle-right me-2"></i> Privacy Policy</a>
                        <a href=""><i class="fas fa-angle-right me-2"></i> Terms and Conditions</a>
                        <a href=""><i class="fas fa-angle-right me-2"></i> Sitemap</a>
                        <a href=""><i class="fas fa-angle-right me-2"></i> Cookie policy</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Footer End -->
    <!-- Copyright Start -->
    <div class="container-fluid copyright text-body py-4">
        <div class="container">
            <div class="row g-4 align-items-center">
                <div class="col-md-6 text-center text-md-end mb-md-0 text-white">
                    <i class="fas fa-copyright me-2"></i><a class="text-white" href="#">SkyAir</a>, All right reserved.
                </div>
                <div class="col-md-6 text-center text-md-start text-white">
                    Designed By <a class="text-white" href="https://www.linkedin.com/in/cristopher-jimenez-jimenez/">Cristopher Jiménez</a>
                </div>
            </div>
        </div>
    </div>
    <!-- Copyright End -->
    <!-- Back to Top -->
    <a href="#" class="btn btn-primary btn-primary-outline-0 btn-lg-square back-to-top"><i class="fa fa-arrow-up"></i></a>
    
    
    <a id="btn-bot" class="btn btn-primary btn-lg-square">
        <i class="fa-solid fa-robot"></i>
    </a>
    <iframe id="bot-window" 
        src="https://copilotstudio.microsoft.com/environments/Default-68519e48-83f3-435f-a38a-1a7aa77ba987/bots/cr899_skyAirBot/webchat?__version__=2"
            frameborder="0"
    class="shadow"></iframe>

    <!-- JavaScript Libraries -->
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script>
        let abierto = false;
        $(document).ready(function () {
            $("#btn-bot").click(function(){
                if(!abierto){
                    $("#bot-window").show();
                }else{
                    $("#bot-window").hide();
                }
                abierto = !abierto;
            })
        });
    </script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    <script src="~/lib/easing/easing.min.js"></script>
    <script src="~/lib/waypoints/waypoints.min.js"></script>
    <script src="~/lib/owlcarousel/owl.carousel.min.js"></script>
    <script src="~/lib/lightbox/js/lightbox.min.js"></script>
    <!-- Template Javascript -->
    <script src="~/js/main.js"></script>
    @RenderSection("Scripts", required: false)
</body>

</html>

MvcSkyAir/Views/Shared/_PanelAdmin.cshtml
<html>
<head>
    <meta charset="utf-8">
    <title>@ViewData["Title"] - SkyAir</title>
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta content="" name="keywords">
    <meta content="" name="description">
    <!-- Icon Font Stylesheet -->
    <script src="https://kit.fontawesome.com/87ad13e327.js" crossorigin="anonymous"></script>
    <!-- Libraries Stylesheet -->
    <link href="~/lib/owlcarousel/assets/owl.carousel.min.css" rel="stylesheet">
    <link href="~/lib/lightbox/css/lightbox.min.css" rel="stylesheet">


    <!-- Customized Bootstrap Stylesheet -->
    <link href="~/lib/bootstrap/dist/css/bootstrap.css" rel="stylesheet">

    <!-- Template Stylesheet -->
    <link href="~/css/style.css" rel="stylesheet">
    <link href="~/css/panel.css" rel="stylesheet">
    @RenderSection("Styles", required: false)
</head>
<body>
    <div class="container-fluid position-relative p-0" >
        <nav class="navbar navbar-expand-lg navbar-light px-4 px-lg-5 py-3 py-lg-0 shadow" style="position:sticky!important;top:0;">
            <a class="navbar-brand p-0"
               asp-controller="Home"
               asp-action="Index">
                <img src="~/img/LOGO_CRIS_provisional.png" alt="Logo" style="filter:none">
            </a>
        </nav>
    </div>
    

    <div class="cont">
        <div class="h-100 bg-black">
            <div class="sidebar">
                <a asp-controller="Usuarios" asp-action="DataVuelos">
                    <i class="fa-solid fa-plane-departure"></i>
                    <span class="txt-option">Vuelos</span>
                </a>
                <a asp-action="Flota" asp-controller="Usuarios">
                    <i class="fa-solid fa-plane-circle-exclamation"></i>
                    <span class="txt-option">Flota</span>
                </a>
                <a asp-action="Logout" asp-controller="Managed">
                    <i class="fa-solid fa-right-from-bracket"></i>
                    <span class="txt-option">Cerrar Sesion</span>
                </a>
            </div>
        </div>
        <div class="container px-5 py-3">
            @RenderBody()
        </div>
    </div>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>


<!-- Template Javascript -->
<script src="~/js/main.js"></script>
@RenderSection("Scripts", required: false)
</body>
</html>

MvcSkyAir/Views/Shared/_PanelAdminLayout.cshtml
<html>
<head>
    <meta charset="utf-8">
    <title>@ViewData["Title"] - SkyAir</title>
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta content="" name="keywords">
    <meta content="" name="description">
    <!-- Icon Font Stylesheet -->
    <script src="https://kit.fontawesome.com/87ad13e327.js" crossorigin="anonymous"></script>
    <!-- Libraries Stylesheet -->
    <link href="~/lib/owlcarousel/assets/owl.carousel.min.css" rel="stylesheet">
    <link href="~/lib/lightbox/css/lightbox.min.css" rel="stylesheet">


    <!-- Customized Bootstrap Stylesheet -->
    <link href="~/lib/bootstrap/dist/css/bootstrap.css" rel="stylesheet">

    <!-- Template Stylesheet -->
    <link href="~/css/style.css" rel="stylesheet">
    <link href="~/css/panel.css" rel="stylesheet">
    @RenderSection("Styles", required: false)
</head>
<body>
    <div class="container-fluid position-relative p-0" >
        <nav class="navbar navbar-expand-lg navbar-light px-4 px-lg-5 py-3 py-lg-0 shadow" style="position:sticky!important;top:0;">
            <a class="navbar-brand p-0"
               asp-controller="Home"
               asp-action="Index">
                <img src="~/img/SkyAir-logo-black.png" alt="Logo" style="filter:none">
            </a>
        </nav>
    </div>
    

    <div class="cont">
        <div class="h-100 bg-black">
            <div class="sidebar">
                <a asp-controller="Usuarios" asp-action="DataVuelos">
                    <i class="fa-solid fa-plane-departure"></i>
                    <span class="txt-option">Vuelos</span>
                </a>
                <a asp-action="Flota" asp-controller="Usuarios">
                    <i class="fa-solid fa-plane-circle-exclamation"></i>
                    <span class="txt-option">Flota</span>
                </a>
                <a asp-action="Logout" asp-controller="Managed">
                    <i class="fa-solid fa-right-from-bracket"></i>
                    <span class="txt-option">Cerrar Sesion</span>
                </a>
            </div>
        </div>
        <div class="container px-5 py-3">
            @RenderBody()
        </div>
    </div>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>


<!-- Template Javascript -->
<script src="~/js/main.js"></script>
@RenderSection("Scripts", required: false)
</body>
</html>